import status from "http-status";
import { Deck } from "../models/decks.js";
import { DeckCard } from "../models/deckCards.js";
import { CardModel } from "../models/cardModels.js";
import { DeckCardModel } from "../models/deckCardModels.js";
import _ from "lodash";

const cardController = {
  createCard: async (req, res, next) => {
    try {

      let {
        user: { id: userId },
        body: {
          name,
          description,
          mana,
          faction,
          rarity,
          life,
          strength,
          power,
        },
      } = req;

      let cardAlreadyExists = await CardModel.findOne({
        where: {
          name: name,
        },
      });

      if (cardAlreadyExists) {
        res.status(400).send({
          message: "This card already exists",
        });

      } else {
        let card = await CardModel.create({
          userId: userId,
          name: name,
          description: description,
          mana,
          faction,
          rarity,
          life,
          strength,
          power,
        });

        res.status(status.CREATED).json({
          status: "success",
          card: card,
        });
      }
    } catch (err) { }
  },
  addCardModelToDeck: async (req, res, next) => {
    try {
      let {
        params: { deckId },
        user: { id: userId },
        body: { cardModelId },
      } = req;

      let deck = await Deck.findOne({
        where: { id: deckId },
      });

      deckId = parseInt(deckId);

      if (deck.userId !== userId) {
        res.status(400).send({
          message: "You do not hold this deck",
        });

      } else {
        let existingCardsLength = await DeckCardModel.count({
          where: {
            deckId: deckId,
          },
        });

        if (existingCardsLength >= 30) {
          res.status(400).send({
            message: "You have reached the total limit of this deck",
          });

        } else {
          let cardExists = await DeckCardModel.findOne({
            where: {
              deckId: deckId,
              cardModelId: cardModelId,
            },
          });

          if (cardExists) {
            res.status(400).send({
              message: "This card already exists in the deck.",
            });

          } else {
            await DeckCardModel.create({
              userId: userId,
              deckId: deckId,
              cardModelId: cardModelId,
            });

            let deckWithCards = await Deck.findOne({
              where: { id: deckId },
              include: [
                {
                  model: DeckCardModel,
                },
              ],
            });

            res.status(status.CREATED).json({
              status: "success",
              deck: deckWithCards,
            });
          }
        }
      }
    } catch (error) {
      console.log(error);
    }
  },
  getAllCardModelOfDeck: async (req, res, next) => {
    try {
      let {
        params: { deckId },
        user: { id: userId },
      } = req;

      let deckWithCards = await Deck.findOne({
        where: { id: deckId },
        include: [
          {
            model: DeckCardModel,
            include: [{ model: CardModel }],
          },
        ],
      });

      res.status(status.OK).json({
        status: "success",
        deck: deckWithCards,
      });
    } catch (err) {
      console.log(err);
    }
  },
  deleteCardFromDeck: async (req, res, next) => {
    try {
      let {
        params: { deckId, cardModelId },
        user: { id: userId },
      } = req;

      let deck = await Deck.findOne({
        where: { id: deckId },
      });

      deckId = parseInt(deckId);
      if (deck.userId !== userId) {
        res.status(400).send({
          message: "You do not hold this deck",
        });

      } else {
        let cardExists = await DeckCardModel.findOne({
          where: {
            deckId: deckId,
            cardModelId: cardModelId,
            userId: userId,
          },
        });

        if (!cardExists) {
          res.status(400).send({
            message: "This card does not exist in the deck.",
          });

        } else {
          await DeckCardModel.destroy({
            where: {
              deckId: deckId,
              cardModelId: cardModelId,
              userId: userId,
            },
          });
        }
        res.status(status.OK).json({
          status: "success",
        });
      }
    } catch (error) { }
  },
  getSpecificCardFromDeck: async (req, res, next) => {
    try {
      let {
        params: { deckId, cardModelId },
        user: { id: userId },
      } = req;

      let deck = await Deck.findOne({
        where: { id: deckId },
      });

      deckId = parseInt(deckId);
      if (deck.userId !== userId) {
        res.status(400).send({
          message: "You do not hold this deck",
        });

      } else {
        let cardExists = await DeckCardModel.findOne({
          where: {
            deckId: deckId,
            cardModelId: cardModelId,
            userId: userId,
          },
          include: [{ model: CardModel }],
        });

        if (!cardExists) {
          res.status(400).send({
            message: "This card does not exist in the deck.",
          });
        } else {
          res.status(status.OK).json({
            status: "success",
            card: cardExists,
          });
        }
      }
    } catch (error) {
      console.log(error);
    }
  },
  getFourRadomCardModelOfDeck: async (req, res, next) => {
    try {
      let {
        params: { deckId },
        user: { id: userId },
      } = req;

      let deckWithCards = await Deck.findOne({
        where: { id: deckId },
        include: [
          {
            model: DeckCardModel,
            include: [{ model: CardModel }],
          },
        ],
      });

      const randomFourCards = _.sampleSize(deckWithCards.DeckCardModels, 4);

      res.status(status.OK).json({
        status: "success",
        deck: randomFourCards,
      });
    } catch (err) {
      console.log(err);
    }
  },
  getAllCardsFromDatabase: async (req, res, next) => {
    try {
      let cards = await CardModel.findAll();

      var obj_arr_appended = cards.map(function (currentValue, Index) {
        currentValue.dataValues.INDEX = Index + 1
        return currentValue
      })

      res.status(status.OK).json({
        status: "success",
        cards: obj_arr_appended,
      });
    } catch (err) {
      console.log(err);
    }
  },
  getAllCardsFromJson: async (req, res, next) => {
    res.status(status.OK).json({
      status: "success",
      cards: cardsJSON,
    });
  }
};

export default cardController;

let cardsJSON = [
  {
    name: "Ponzi King",
    image: "",
    description: "",
    symbol: "",
    collectionName: "",
    collectionFamily: "",
    mana: 5,
    attack: 2,
    hp: 3,
    specification: "Reduce the mana of a random card by 1.",
    faction: "Evil",
    rarity: "Common",
    cardType: "Minion",
    life: "",
    strength: "",
    power: "",
    sellerFeeBasisPoints: "",
    creatorAddress: "",
    creatorShare: "",
    fileUri: "",
    fileType: "",
  },
  {
    name: "Bogdragon",
    image: "",
    description: "",
    symbol: "",
    collectionName: "",
    collectionFamily: "",
    mana: 6,
    attack: 5,
    hp: 10,
    specification: "Deal 1 damage to all of the opponent minions.",
    faction: "Creature",
    rarity: "Rare",
    cardType: "Minion",
    life: "",
    strength: "",
    power: "",
    sellerFeeBasisPoints: "",
    creatorAddress: "",
    creatorShare: "",
    fileUri: "",
    fileType: "",
  },
  {
    name: "Howling Wizard",
    image: "",
    description: "",
    symbol: "",
    collectionName: "",
    collectionFamily: "",
    mana: 6,
    attack: 5,
    hp: 10,
    specification: "Taunt.",
    faction: "Magic",
    rarity: "Epic",
    cardType: "Minion",
    life: "",
    strength: "",
    power: "",
    sellerFeeBasisPoints: "",
    creatorAddress: "",
    creatorShare: "",
    fileUri: "",
    fileType: "",
  },
  {
    name: "Amchor the Alpinist",
    image: "",
    description: "",
    symbol: "",
    collectionName: "",
    collectionFamily: "",
    mana: 6,
    attack: 2,
    hp: 5,
    specification: "Add 2 attack points to one minion.",
    faction: "Citizen",
    rarity: "Epic",
    cardType: "Minion",
    life: "",
    strength: "",
    power: "",
    sellerFeeBasisPoints: "",
    creatorAddress: "",
    creatorShare: "",
    fileUri: "",
    fileType: "",
  },
  {
    name: "Cheemsatoshi",
    image: "",
    description: "",
    symbol: "",
    collectionName: "",
    collectionFamily: "",
    mana: 7,
    attack: 7,
    hp: 7,
    specification: "Draw a card.",
    faction: "Magic",
    rarity: "Legendary",
    cardType: "Minion",
    life: "",
    strength: "",
    power: "",
    sellerFeeBasisPoints: "",
    creatorAddress: "",
    creatorShare: "",
    fileUri: "",
    fileType: "",
  },
  {
    name: "Tabzen the Tyrant",
    image: "",
    description: "",
    symbol: "",
    collectionName: "",
    collectionFamily: "",
    mana: 7,
    attack: 7,
    hp: 5,
    specification: "Destroy a random opponent minion.",
    faction: "Evil",
    rarity: "Legendary",
    cardType: "Minion",
    life: "",
    strength: "",
    power: "",
    sellerFeeBasisPoints: "",
    creatorAddress: "",
    creatorShare: "",
    fileUri: "",
    fileType: "",
  },
  {
    name: "Kermit the Degen",
    image: "",
    description: "",
    symbol: "",
    collectionName: "",
    collectionFamily: "",
    mana: 7,
    attack: 7,
    hp: 5,
    specification: "Freeze a random opponent minion for 2 turns.",
    faction: "Magic",
    rarity: "Legendary",
    cardType: "Minion",
    life: "",
    strength: "",
    power: "",
    sellerFeeBasisPoints: "",
    creatorAddress: "",
    creatorShare: "",
    fileUri: "",
    fileType: "",
  },
  {
    name: "Melon Piggo",
    image: "",
    description: "",
    symbol: "",
    collectionName: "",
    collectionFamily: "",
    mana: 7,
    attack: 7,
    hp: 5,
    specification: "Deal 1 damage to all of the opponent minions and 3 to their god.",
    faction: "Creature",
    rarity: "Legendary",
    cardType: "Minion",
    life: "",
    strength: "",
    power: "",
    sellerFeeBasisPoints: "",
    creatorAddress: "",
    creatorShare: "",
    fileUri: "",
    fileType: "",
  },
  {
    name: "Natzuko the Assassin",
    image: "",
    description: "",
    symbol: "",
    collectionName: "",
    collectionFamily: "",
    mana: 7,
    attack: 7,
    hp: 5,
    specification: "Your god gains +3 HP and a random card is added into your hand.",
    faction: "Evil",
    rarity: "Legendary",
    cardType: "Minion",
    life: "",
    strength: "",
    power: "",
    sellerFeeBasisPoints: "",
    creatorAddress: "",
    creatorShare: "",
    fileUri: "",
    fileType: "",
  },
  {
    name: "Firecrab",
    image: "",
    description: "",
    symbol: "",
    collectionName: "",
    collectionFamily: "",
    mana: 2,
    attack: 1,
    hp: 1,
    specification: "Draw a card.",
    faction: "Creature",
    rarity: "Common",
    cardType: "Minion",
    life: "",
    strength: "",
    power: "",
    sellerFeeBasisPoints: "",
    creatorAddress: "",
    creatorShare: "",
    fileUri: "",
    fileType: "",
  },
  {
    name: "Dogegorgon",
    image: "",
    description: "",
    symbol: "",
    collectionName: "",
    collectionFamily: "",
    mana: 4,
    attack: 5,
    hp: 2,
    specification: "Draw a card.",
    faction: "Evil",
    rarity: "Epic",
    cardType: "Minion",
    life: "",
    strength: "",
    power: "",
    sellerFeeBasisPoints: "",
    creatorAddress: "",
    creatorShare: "",
    fileUri: "",
    fileType: "",
  },
  {
    name: "Pyramid Cheem",
    image: "",
    description: "",
    symbol: "",
    collectionName: "",
    collectionFamily: "",
    mana: 5,
    attack: 2,
    hp: 1,
    specification: "-1 HP to a random opponents minion each turn.",
    faction: "Neutral",
    rarity: "Rare",
    cardType: "Minion",
    life: "",
    strength: "",
    power: "",
    sellerFeeBasisPoints: "",
    creatorAddress: "",
    creatorShare: "",
    fileUri: "",
    fileType: "",
  },
  {
    name: "Boxer the Warrior",
    image: "",
    description: "",
    symbol: "",
    collectionName: "",
    collectionFamily: "",
    mana: 3,
    attack: 3,
    hp: 3,
    specification: "Opponent is unable to attack their next turn.",
    faction: "Citizen",
    rarity: "Epic",
    cardType: "Minion",
    life: "",
    strength: "",
    power: "",
    sellerFeeBasisPoints: "",
    creatorAddress: "",
    creatorShare: "",
    fileUri: "",
    fileType: "",
  },
  {
    name: "Avalanche Shyeti",
    image: "",
    description: "",
    symbol: "",
    collectionName: "",
    collectionFamily: "",
    mana: 1,
    attack: 1,
    hp: 1,
    specification: "Oppenent has a 30% chance to miss their attack.",
    faction: "Creature",
    rarity: "Common",
    cardType: "Minion",
    life: "",
    strength: "",
    power: "",
    sellerFeeBasisPoints: "",
    creatorAddress: "",
    creatorShare: "",
    fileUri: "",
    fileType: "",
  },
  {
    name: "Master Shibineer",
    image: "",
    description: "",
    symbol: "",
    collectionName: "",
    collectionFamily: "",
    mana: 1,
    attack: 2,
    hp: 2,
    specification: "Deal 1 damage to an enemy creature.",
    faction: "Citizen",
    rarity: "Rare",
    cardType: "Minion",
    life: "",
    strength: "",
    power: "",
    sellerFeeBasisPoints: "",
    creatorAddress: "",
    creatorShare: "",
    fileUri: "",
    fileType: "",
  },
  {
    name: "Fiksu the Archeress",
    image: "",
    description: "",
    symbol: "",
    collectionName: "",
    collectionFamily: "",
    mana: 3,
    attack: 3,
    hp: 1,
    specification: "Upon death, 1 damage is dealt to all opponent minions.",
    faction: "Citizen",
    rarity: "Epic",
    cardType: "Minion",
    life: "",
    strength: "",
    power: "",
    sellerFeeBasisPoints: "",
    creatorAddress: "",
    creatorShare: "",
    fileUri: "",
    fileType: "",
  },
  {
    name: "Magma Shibdozer",
    image: "",
    description: "",
    symbol: "",
    collectionName: "",
    collectionFamily: "",
    mana: 1,
    attack: 2,
    hp: 2,
    specification: "Taunt.",
    faction: "Creature",
    rarity: "Common",
    cardType: "Minion",
    life: "",
    strength: "",
    power: "",
    sellerFeeBasisPoints: "",
    creatorAddress: "",
    creatorShare: "",
    fileUri: "",
    fileType: "",
  },
  {
    name: "Bonk",
    image: "",
    description: "",
    symbol: "",
    collectionName: "",
    collectionFamily: "",
    mana: 7,
    attack: 4,
    hp: 9,
    specification: "Whenever Bonk takes damage, double its attack.",
    faction: "Neutral",
    rarity: "Rare",
    cardType: "Minion",
    life: "",
    strength: "",
    power: "",
    sellerFeeBasisPoints: "",
    creatorAddress: "",
    creatorShare: "",
    fileUri: "",
    fileType: "",
  },
  {
    name: "Merchant Cheemsy",
    image: "",
    description: "",
    symbol: "",
    collectionName: "",
    collectionFamily: "",
    mana: 5,
    attack: 2,
    hp: 2,
    specification: "Draw 2 cards.",
    faction: "Citizen",
    rarity: "Common",
    cardType: "Minion",
    life: "",
    strength: "",
    power: "",
    sellerFeeBasisPoints: "",
    creatorAddress: "",
    creatorShare: "",
    fileUri: "",
    fileType: "",
  },
  {
    name: "Mystic Spy",
    image: "",
    description: "",
    symbol: "",
    collectionName: "",
    collectionFamily: "",
    mana: 3,
    attack: 2,
    hp: 1,
    specification: "-2 HP to all opponent minions.",
    faction: "Evil",
    rarity: "Epic",
    cardType: "Minion",
    life: "",
    strength: "",
    power: "",
    sellerFeeBasisPoints: "",
    creatorAddress: "",
    creatorShare: "",
    fileUri: "",
    fileType: "",
  },
  {
    name: "Borg Hound",
    image: "",
    description: "",
    symbol: "",
    collectionName: "",
    collectionFamily: "",
    mana: 1,
    attack: 1,
    hp: 2,
    specification: "Upon death, a random card is added into your hand.",
    faction: "Magic",
    rarity: "Rare",
    cardType: "Minion",
    life: "",
    strength: "",
    power: "",
    sellerFeeBasisPoints: "",
    creatorAddress: "",
    creatorShare: "",
    fileUri: "",
    fileType: "",
  },
  {
    name: "Degenape",
    image: "",
    description: "",
    symbol: "",
    collectionName: "",
    collectionFamily: "",
    mana: 2,
    attack: 2,
    hp: 2,
    specification: "Whenever a friendly minion dies, this creature gets +1 attack.",
    faction: "Creature",
    rarity: "Rare",
    cardType: "Minion",
    life: "",
    strength: "",
    power: "",
    sellerFeeBasisPoints: "",
    creatorAddress: "",
    creatorShare: "",
    fileUri: "",
    fileType: "",
  },
  {
    name: "Karma the Enchanted",
    image: "",
    description: "",
    symbol: "",
    collectionName: "",
    collectionFamily: "",
    mana: 1,
    attack: 2,
    hp: 2,
    specification: "Give +2 HP to your god.",
    faction: "Magic",
    rarity: "Common",
    cardType: "Minion",
    life: "",
    strength: "",
    power: "",
    sellerFeeBasisPoints: "",
    creatorAddress: "",
    creatorShare: "",
    fileUri: "",
    fileType: "",
  },
  {
    name: "Ragnar the Hacker",
    image: "",
    description: "",
    symbol: "",
    collectionName: "",
    collectionFamily: "",
    mana: 2,
    attack: 2,
    hp: 2,
    specification: "Give +1 HP to a random minion.",
    faction: "Magic",
    rarity: "Common",
    cardType: "Minion",
    life: "",
    strength: "",
    power: "",
    sellerFeeBasisPoints: "",
    creatorAddress: "",
    creatorShare: "",
    fileUri: "",
    fileType: "",
  },
  {
    name: "Composability God",
    image: "",
    description: "",
    symbol: "",
    collectionName: "",
    collectionFamily: "",
    mana: 5,
    attack: 3,
    hp: 6,
    specification: "One-hit kill Boxer the Warrior.",
    faction: "Magic",
    rarity: "Rare",
    cardType: "Minion",
    life: "",
    strength: "",
    power: "",
    sellerFeeBasisPoints: "",
    creatorAddress: "",
    creatorShare: "",
    fileUri: "",
    fileType: "",
  },
  {
    name: "Bonk Whale",
    image: "",
    description: "",
    symbol: "",
    collectionName: "",
    collectionFamily: "",
    mana: 7,
    attack: 5,
    hp: 7,
    specification: "Whenever your enemy plays a spell, 2 cards are added to your hand.",
    faction: "Creature",
    rarity: "Legendary",
    cardType: "Minion",
    life: "",
    strength: "",
    power: "",
    sellerFeeBasisPoints: "",
    creatorAddress: "",
    creatorShare: "",
    fileUri: "",
    fileType: "",
  },
  {
    name: "Ape Warrior",
    image: "",
    description: "",
    symbol: "",
    collectionName: "",
    collectionFamily: "",
    mana: 3,
    attack: 3,
    hp: 3,
    specification: "Destroy a friendly minion and add its stats to this card.",
    faction: "Creature",
    rarity: "Rare",
    cardType: "Minion",
    life: "",
    strength: "",
    power: "",
    sellerFeeBasisPoints: "",
    creatorAddress: "",
    creatorShare: "",
    fileUri: "",
    fileType: "",
  },
  {
    name: "Sir Knight Cheemsy",
    image: "",
    description: "",
    symbol: "",
    collectionName: "",
    collectionFamily: "",
    mana: 8,
    attack: 2,
    hp: 11,
    specification: "Whenever your god takes damage, deal 2 damage to each opponent creature.",
    faction: "Citizen",
    rarity: "Common",
    cardType: "Minion",
    life: "",
    strength: "",
    power: "",
    sellerFeeBasisPoints: "",
    creatorAddress: "",
    creatorShare: "",
    fileUri: "",
    fileType: "",
  },
  {
    name: "Maximus Cheemsius II",
    image: "",
    description: "",
    symbol: "",
    collectionName: "",
    collectionFamily: "",
    mana: 3,
    attack: 2,
    hp: 3,
    specification: "Give +1 HP to a friendly minion.",
    faction: "Citizen",
    rarity: "Common",
    cardType: "Minion",
    life: "",
    strength: "",
    power: "",
    sellerFeeBasisPoints: "",
    creatorAddress: "",
    creatorShare: "",
    fileUri: "",
    fileType: "",
  },
  {
    name: "Old Farmer Cheemsy",
    image: "",
    description: "",
    symbol: "",
    collectionName: "",
    collectionFamily: "",
    mana: 1,
    attack: 1,
    hp: 1,
    specification: "Draw a card.",
    faction: "Citizen",
    rarity: "Common",
    cardType: "Minion",
    life: "",
    strength: "",
    power: "",
    sellerFeeBasisPoints: "",
    creatorAddress: "",
    creatorShare: "",
    fileUri: "",
    fileType: "",
  },
  {
    name: "Baby Cheems",
    image: "",
    description: "",
    symbol: "",
    collectionName: "",
    collectionFamily: "",
    mana: 1,
    attack: 1,
    hp: 2,
    specification: "After each round, +2 HP is added to an injured friendly minion.",
    faction: "Neutral",
    rarity: "Common",
    cardType: "Minion",
    life: "",
    strength: "",
    power: "",
    sellerFeeBasisPoints: "",
    creatorAddress: "",
    creatorShare: "",
    fileUri: "",
    fileType: "",
  },
  {
    name: "Enchanted Inucorn",
    image: "",
    description: "",
    symbol: "",
    collectionName: "",
    collectionFamily: "",
    mana: 1,
    attack: 1,
    hp: 1,
    specification: "Upon death, a random card is added into your hand.",
    faction: "Magic",
    rarity: "Common",
    cardType: "Minion",
    life: "",
    strength: "",
    power: "",
    sellerFeeBasisPoints: "",
    creatorAddress: "",
    creatorShare: "",
    fileUri: "",
    fileType: "",
  },
  {
    name: "Duke the Investor",
    image: "",
    description: "",
    symbol: "",
    collectionName: "",
    collectionFamily: "",
    mana: 2,
    attack: 2,
    hp: 2,
    specification: "Draw a card.",
    faction: "Citizen",
    rarity: "Common",
    cardType: "Minion",
    life: "",
    strength: "",
    power: "",
    sellerFeeBasisPoints: "",
    creatorAddress: "",
    creatorShare: "",
    fileUri: "",
    fileType: "",
  },
  {
    name: "Dungeon Shiborc",
    image: "",
    description: "",
    symbol: "",
    collectionName: "",
    collectionFamily: "",
    mana: 2,
    attack: 1,
    hp: 3,
    specification: "Reduce the mana of a random card by 2.",
    faction: "Evil",
    rarity: "Common",
    cardType: "Minion",
    life: "",
    strength: "",
    power: "",
    sellerFeeBasisPoints: "",
    creatorAddress: "",
    creatorShare: "",
    fileUri: "",
    fileType: "",
  },
  {
    name: "Water Shibagician",
    image: "",
    description: "",
    symbol: "",
    collectionName: "",
    collectionFamily: "",
    mana: 2,
    attack: 1,
    hp: 1,
    specification: "Upon death, 2 random cards are added into each players hand.",
    faction: "Magic",
    rarity: "Common",
    cardType: "Minion",
    life: "",
    strength: "",
    power: "",
    sellerFeeBasisPoints: "",
    creatorAddress: "",
    creatorShare: "",
    fileUri: "",
    fileType: "",
  },
  {
    name: "Cryptographer",
    image: "",
    description: "",
    symbol: "",
    collectionName: "",
    collectionFamily: "",
    mana: 2,
    attack: 2,
    hp: 3,
    specification: "Whenever your enemy plays a spell, this minion will gain +1 HP.",
    faction: "Citizen",
    rarity: "Common",
    cardType: "Minion",
    life: "",
    strength: "",
    power: "",
    sellerFeeBasisPoints: "",
    creatorAddress: "",
    creatorShare: "",
    fileUri: "",
    fileType: "",
  },
  {
    name: "Monkey King",
    image: "",
    description: "",
    symbol: "",
    collectionName: "",
    collectionFamily: "",
    mana: 2,
    attack: 2,
    hp: 3,
    specification: "Taunt",
    faction: "Creature",
    rarity: "Common",
    cardType: "Minion",
    life: "",
    strength: "",
    power: "",
    sellerFeeBasisPoints: "",
    creatorAddress: "",
    creatorShare: "",
    fileUri: "",
    fileType: "",
  },
  {
    name: "Angry Beak",
    image: "",
    description: "",
    symbol: "",
    collectionName: "",
    collectionFamily: "",
    mana: 2,
    attack: 2,
    hp: 2,
    specification: "Shield",
    faction: "Creature",
    rarity: "Common",
    cardType: "Minion",
    life: "",
    strength: "",
    power: "",
    sellerFeeBasisPoints: "",
    creatorAddress: "",
    creatorShare: "",
    fileUri: "",
    fileType: "",
  },
  {
    name: "Zen Master Cheemsy",
    image: "",
    description: "",
    symbol: "",
    collectionName: "",
    collectionFamily: "",
    mana: 3,
    attack: 2,
    hp: 1,
    specification: "Lightning",
    faction: "Magic",
    rarity: "Common",
    cardType: "Minion",
    life: "",
    strength: "",
    power: "",
    sellerFeeBasisPoints: "",
    creatorAddress: "",
    creatorShare: "",
    fileUri: "",
    fileType: "",
  },
  {
    name: "Desert Sphinx",
    image: "",
    description: "",
    symbol: "",
    collectionName: "",
    collectionFamily: "",
    mana: 3,
    attack: 3,
    hp: 2,
    specification: "Upon death, a random card is added into your hand.",
    faction: "Creature",
    rarity: "Common",
    cardType: "Minion",
    life: "",
    strength: "",
    power: "",
    sellerFeeBasisPoints: "",
    creatorAddress: "",
    creatorShare: "",
    fileUri: "",
    fileType: "",
  },
  {
    name: "Dash the Courier",
    image: "",
    description: "",
    symbol: "",
    collectionName: "",
    collectionFamily: "",
    mana: 3,
    attack: 2,
    hp: 1,
    specification: "-1 HP to all opponent minions.",
    faction: "Citizen",
    rarity: "Common",
    cardType: "Minion",
    life: "",
    strength: "",
    power: "",
    sellerFeeBasisPoints: "",
    creatorAddress: "",
    creatorShare: "",
    fileUri: "",
    fileType: "",
  },
  {
    name: "Jungle Shibsplorer",
    image: "",
    description: "",
    symbol: "",
    collectionName: "",
    collectionFamily: "",
    mana: 3,
    attack: 3,
    hp: 3,
    specification: "Upon death, a random card is added into your hand.",
    faction: "Citizen",
    rarity: "Common",
    cardType: "Minion",
    life: "",
    strength: "",
    power: "",
    sellerFeeBasisPoints: "",
    creatorAddress: "",
    creatorShare: "",
    fileUri: "",
    fileType: "",
  },
  {
    name: "Weapons Doggodev",
    image: "",
    description: "",
    symbol: "",
    collectionName: "",
    collectionFamily: "",
    mana: 4,
    attack: 4,
    hp: 4,
    specification: "Add a copy to the last minion you played into your hands.",
    faction: "Magic",
    rarity: "Common",
    cardType: "Minion",
    life: "",
    strength: "",
    power: "",
    sellerFeeBasisPoints: "",
    creatorAddress: "",
    creatorShare: "",
    fileUri: "",
    fileType: "",
  },
  {
    name: "Regulatoor Hound",
    image: "",
    description: "",
    symbol: "",
    collectionName: "",
    collectionFamily: "",
    mana: 4,
    attack: 2,
    hp: 3,
    specification: "Set a random enemy minion attack to 1.",
    faction: "Citizen",
    rarity: "Common",
    cardType: "Minion",
    life: "",
    strength: "",
    power: "",
    sellerFeeBasisPoints: "",
    creatorAddress: "",
    creatorShare: "",
    fileUri: "",
    fileType: "",
  },
  {
    name: "Fanged Chaos",
    image: "",
    description: "",
    symbol: "",
    collectionName: "",
    collectionFamily: "",
    mana: 4,
    attack: 1,
    hp: 1,
    specification: "Give +1 HP to your god.",
    faction: "Evil",
    rarity: "Common",
    cardType: "Minion",
    life: "",
    strength: "",
    power: "",
    sellerFeeBasisPoints: "",
    creatorAddress: "",
    creatorShare: "",
    fileUri: "",
    fileType: "",
  },
  {
    name: "Hopium Trader",
    image: "",
    description: "",
    symbol: "",
    collectionName: "",
    collectionFamily: "",
    mana: 5,
    attack: 2,
    hp: 2,
    specification: "Draw 2 cards.",
    faction: "Citizen",
    rarity: "Common",
    cardType: "Minion",
    life: "",
    strength: "",
    power: "",
    sellerFeeBasisPoints: "",
    creatorAddress: "",
    creatorShare: "",
    fileUri: "",
    fileType: "",
  },
  {
    name: "Snow Shoober",
    image: "",
    description: "",
    symbol: "",
    collectionName: "",
    collectionFamily: "",
    mana: 5,
    attack: 4,
    hp: 1,
    specification: "-2 HP to a random opponent minion.",
    faction: "Citizen",
    rarity: "Common",
    cardType: "Minion",
    life: "",
    strength: "",
    power: "",
    sellerFeeBasisPoints: "",
    creatorAddress: "",
    creatorShare: "",
    fileUri: "",
    fileType: "",
  },
  {
    name: "Potion Shiller",
    image: "",
    description: "",
    symbol: "",
    collectionName: "",
    collectionFamily: "",
    mana: 6,
    attack: 5,
    hp: 2,
    specification: "Whenever you attack with this minion, give +2 attack to a random friendly creature.",
    faction: "Evil",
    rarity: "Common",
    cardType: "Minion",
    life: "",
    strength: "",
    power: "",
    sellerFeeBasisPoints: "",
    creatorAddress: "",
    creatorShare: "",
    fileUri: "",
    fileType: "",
  },
  {
    name: "Caesar the Gaurdian",
    image: "",
    description: "",
    symbol: "",
    collectionName: "",
    collectionFamily: "",
    mana: 7,
    attack: 5,
    hp: 7,
    specification: "Set a random opponent minion to 2 HP.",
    faction: "Citizen",
    rarity: "Common",
    cardType: "Minion",
    life: "",
    strength: "",
    power: "",
    sellerFeeBasisPoints: "",
    creatorAddress: "",
    creatorShare: "",
    fileUri: "",
    fileType: "",
  },
  {
    name: "Lucky Ancient",
    image: "",
    description: "",
    symbol: "",
    collectionName: "",
    collectionFamily: "",
    mana: 7,
    attack: 7,
    hp: 7,
    specification: "When played, there is a 50% chance to deal 3 damage to the enemy god.",
    faction: "Magic",
    rarity: "Common",
    cardType: "Minion",
    life: "",
    strength: "",
    power: "",
    sellerFeeBasisPoints: "",
    creatorAddress: "",
    creatorShare: "",
    fileUri: "",
    fileType: "",
  },
  {
    name: "Cheems Hammer",
    image: "",
    description: "",
    symbol: "",
    collectionName: "",
    collectionFamily: "",
    mana: 1,
    attack: 2,
    hp: 2,
    specification: "Upon death, your god recieves +4 HP.",
    faction: "Magic",
    rarity: "Rare",
    cardType: "Minion",
    life: "",
    strength: "",
    power: "",
    sellerFeeBasisPoints: "",
    creatorAddress: "",
    creatorShare: "",
    fileUri: "",
    fileType: "",
  },
  {
    name: "Grim Sheeber",
    image: "",
    description: "",
    symbol: "",
    collectionName: "",
    collectionFamily: "",
    mana: 1,
    attack: 2,
    hp: 1,
    specification: "Confuse a random enemy minion.",
    faction: "Evil",
    rarity: "Rare",
    cardType: "Minion",
    life: "",
    strength: "",
    power: "",
    sellerFeeBasisPoints: "",
    creatorAddress: "",
    creatorShare: "",
    fileUri: "",
    fileType: "",
  },
  {
    name: "Armored Talons",
    image: "",
    description: "",
    symbol: "",
    collectionName: "",
    collectionFamily: "",
    mana: 2,
    attack: 2,
    hp: 2,
    specification: "Whenever a friendly minion dies, this creature gets +1 HP.",
    faction: "Creature",
    rarity: "Rare",
    cardType: "Minion",
    life: "",
    strength: "",
    power: "",
    sellerFeeBasisPoints: "",
    creatorAddress: "",
    creatorShare: "",
    fileUri: "",
    fileType: "",
  },
  {
    name: "Diesel the Demon",
    image: "",
    description: "",
    symbol: "",
    collectionName: "",
    collectionFamily: "",
    mana: 3,
    attack: 3,
    hp: 3,
    specification: "Destroy a friendly minion and this creature get its strength and health.",
    faction: "Evil",
    rarity: "Rare",
    cardType: "Minion",
    life: "",
    strength: "",
    power: "",
    sellerFeeBasisPoints: "",
    creatorAddress: "",
    creatorShare: "",
    fileUri: "",
    fileType: "",
  },
  {
    name: "Gladiator Shiborc",
    image: "",
    description: "",
    symbol: "",
    collectionName: "",
    collectionFamily: "",
    mana: 3,
    attack: 2,
    hp: 4,
    specification: "If this is your only minion on the board, it gets +2 attack.",
    faction: "Citizen",
    rarity: "Rare",
    cardType: "Minion",
    life: "",
    strength: "",
    power: "",
    sellerFeeBasisPoints: "",
    creatorAddress: "",
    creatorShare: "",
    fileUri: "",
    fileType: "",
  },
  {
    name: "Brutus the Bonker",
    image: "",
    description: "",
    symbol: "",
    collectionName: "",
    collectionFamily: "",
    mana: 4,
    attack: 2,
    hp: 4,
    specification: "Reduce the mana of all cards in your hands by 1.",
    faction: "Citizen",
    rarity: "Rare",
    cardType: "Minion",
    life: "",
    strength: "",
    power: "",
    sellerFeeBasisPoints: "",
    creatorAddress: "",
    creatorShare: "",
    fileUri: "",
    fileType: "",
  },
  {
    name: "Mercenary Shibtaur",
    image: "",
    description: "",
    symbol: "",
    collectionName: "",
    collectionFamily: "",
    mana: 4,
    attack: 4,
    hp: 3,
    specification: "Confuse a random enemy minion.",
    faction: "Citizen",
    rarity: "Rare",
    cardType: "Minion",
    life: "",
    strength: "",
    power: "",
    sellerFeeBasisPoints: "",
    creatorAddress: "",
    creatorShare: "",
    fileUri: "",
    fileType: "",
  },
  {
    name: "Ancient Sword",
    image: "",
    description: "",
    symbol: "",
    collectionName: "",
    collectionFamily: "",
    mana: 5,
    attack: 5,
    hp: 2,
    specification: "Lightning",
    faction: "Magic",
    rarity: "Rare",
    cardType: "Minion",
    life: "",
    strength: "",
    power: "",
    sellerFeeBasisPoints: "",
    creatorAddress: "",
    creatorShare: "",
    fileUri: "",
    fileType: "",
  },
  {
    name: "Sandune Snarler",
    image: "",
    description: "",
    symbol: "",
    collectionName: "",
    collectionFamily: "",
    mana: 6,
    attack: 5,
    hp: 2,
    specification: "Destroy a random enemy minion with health 3 or less.",
    faction: "Evil",
    rarity: "Rare",
    cardType: "Minion",
    life: "",
    strength: "",
    power: "",
    sellerFeeBasisPoints: "",
    creatorAddress: "",
    creatorShare: "",
    fileUri: "",
    fileType: "",
  },
  {
    name: "Howling Oaks",
    image: "",
    description: "",
    symbol: "",
    collectionName: "",
    collectionFamily: "",
    mana: 7,
    attack: 6,
    hp: 6,
    specification: "Deal 3 damage to a selected minion.",
    faction: "Creature",
    rarity: "Rare",
    cardType: "Minion",
    life: "",
    strength: "",
    power: "",
    sellerFeeBasisPoints: "",
    creatorAddress: "",
    creatorShare: "",
    fileUri: "",
    fileType: "",
  },
  {
    name: "Savant Shibatician",
    image: "",
    description: "",
    symbol: "",
    collectionName: "",
    collectionFamily: "",
    mana: 2,
    attack: 2,
    hp: 2,
    specification: "All of your confused minions recieve +2 health.",
    faction: "Magic",
    rarity: "Epic",
    cardType: "Minion",
    life: "",
    strength: "",
    power: "",
    sellerFeeBasisPoints: "",
    creatorAddress: "",
    creatorShare: "",
    fileUri: "",
    fileType: "",
  },
  {
    name: "Gnarling Swamp Spammer",
    image: "",
    description: "",
    symbol: "",
    collectionName: "",
    collectionFamily: "",
    mana: 2,
    attack: 1,
    hp: 1,
    specification: "Whenever a spell is cast, give a copy of it to the other player.",
    faction: "Evil",
    rarity: "Legendary",
    cardType: "Minion",
    life: "",
    strength: "",
    power: "",
    sellerFeeBasisPoints: "",
    creatorAddress: "",
    creatorShare: "",
    fileUri: "",
    fileType: "",
  },
  {
    name: "Rug Pull",
    image: "",
    description: "",
    symbol: "",
    collectionName: "",
    collectionFamily: "",
    mana: 4,
    attack: null,
    hp: null,
    specification: "-2 HP to all of your opponents minions.",
    faction: "Evil",
    rarity: "Legendary",
    cardType: "Spell",
    life: "",
    strength: "",
    power: "",
    sellerFeeBasisPoints: "",
    creatorAddress: "",
    creatorShare: "",
    fileUri: "",
    fileType: "",
  },
  {
    name: "",
    image: "",
    description: "",
    symbol: "",
    collectionName: "",
    collectionFamily: "",
    mana: 0,
    attack: null,
    hp: null,
    specification: "",
    faction: "",
    rarity: "",
    cardType: "Spell",
    life: "",
    strength: "",
    power: "",
    sellerFeeBasisPoints: "",
    creatorAddress: "",
    creatorShare: "",
    fileUri: "",
    fileType: "",
  },
  {
    name: "Stacking Sats",
    image: "",
    description: "",
    symbol: "",
    collectionName: "",
    collectionFamily: "",
    mana: 3,
    attack: null,
    hp: null,
    specification: "Add 1 HP to each friendly minion.",
    faction: "Neutral",
    rarity: "Epic",
    cardType: "Spell",
    life: "",
    strength: "",
    power: "",
    sellerFeeBasisPoints: "",
    creatorAddress: "",
    creatorShare: "",
    fileUri: "",
    fileType: "",
  },
  {
    name: "Mana Airdrop",
    image: "",
    description: "",
    symbol: "",
    collectionName: "",
    collectionFamily: "",
    mana: 2,
    attack: null,
    hp: null,
    specification: "Deal 1 damage point to your opponents god and reduce the cost of spells in your hand by 1.",
    faction: "Neutral",
    rarity: "Epic",
    cardType: "Spell",
    life: "",
    strength: "",
    power: "",
    sellerFeeBasisPoints: "",
    creatorAddress: "",
    creatorShare: "",
    fileUri: "",
    fileType: "",
  },
  {
    name: "Flashloan Attack",
    image: "",
    description: "",
    symbol: "",
    collectionName: "",
    collectionFamily: "",
    mana: 1,
    attack: null,
    hp: null,
    specification: "2/3 chance to reduce opponents gods HP by 2.",
    faction: "Magic",
    rarity: "Common",
    cardType: "Spell",
    life: "",
    strength: "",
    power: "",
    sellerFeeBasisPoints: "",
    creatorAddress: "",
    creatorShare: "",
    fileUri: "",
    fileType: "",
  },
  {
    name: "Shiba Freeze",
    image: "",
    description: "",
    symbol: "",
    collectionName: "",
    collectionFamily: "",
    mana: 1,
    attack: null,
    hp: null,
    specification: "Freeze a minion and deal 1 damage to it.",
    faction: "Magic",
    rarity: "Common",
    cardType: "Spell",
    life: "",
    strength: "",
    power: "",
    sellerFeeBasisPoints: "",
    creatorAddress: "",
    creatorShare: "",
    fileUri: "",
    fileType: "",
  },
  {
    name: "Sellout",
    image: "",
    description: "",
    symbol: "",
    collectionName: "",
    collectionFamily: "",
    mana: 1,
    attack: null,
    hp: null,
    specification: "Add 1 HP to each friendly minion.",
    faction: "Citizen",
    rarity: "Common",
    cardType: "Spell",
    life: "",
    strength: "",
    power: "",
    sellerFeeBasisPoints: "",
    creatorAddress: "",
    creatorShare: "",
    fileUri: "",
    fileType: "",
  },
  {
    name: "FUD",
    image: "",
    description: "",
    symbol: "",
    collectionName: "",
    collectionFamily: "",
    mana: 1,
    attack: null,
    hp: null,
    specification: "-1 HP to all opponent minions.",
    faction: "Evil",
    rarity: "Epic",
    cardType: "Spell",
    life: "",
    strength: "",
    power: "",
    sellerFeeBasisPoints: "",
    creatorAddress: "",
    creatorShare: "",
    fileUri: "",
    fileType: "",
  },
  {
    name: "Smart Contacts",
    image: "",
    description: "",
    symbol: "",
    collectionName: "",
    collectionFamily: "",
    mana: 1,
    attack: null,
    hp: null,
    specification: "Add 2 HP and 1 attack to a random friendly minion.",
    faction: "Neutral",
    rarity: "Legendary",
    cardType: "Spell",
    life: "",
    strength: "",
    power: "",
    sellerFeeBasisPoints: "",
    creatorAddress: "",
    creatorShare: "",
    fileUri: "",
    fileType: "",
  },
  {
    name: "Copy Pasta",
    image: "",
    description: "",
    symbol: "",
    collectionName: "",
    collectionFamily: "",
    mana: 2,
    attack: null,
    hp: null,
    specification: "Duplicate the lowest mana cost minion in your hand.",
    faction: "Neutral",
    rarity: "Epic",
    cardType: "Spell",
    life: "",
    strength: "",
    power: "",
    sellerFeeBasisPoints: "",
    creatorAddress: "",
    creatorShare: "",
    fileUri: "",
    fileType: "",
  },
  {
    name: "Maximum TPS",
    image: "",
    description: "",
    symbol: "",
    collectionName: "",
    collectionFamily: "",
    mana: 1,
    attack: null,
    hp: null,
    specification: "Add 2 attack points to all friendly minions.",
    faction: "Magic",
    rarity: "Legendary",
    cardType: "Spell",
    life: "",
    strength: "",
    power: "",
    sellerFeeBasisPoints: "",
    creatorAddress: "",
    creatorShare: "",
    fileUri: "",
    fileType: "",
  },
  {
    name: "Mint",
    image: "",
    description: "",
    symbol: "",
    collectionName: "",
    collectionFamily: "",
    mana: 1,
    attack: null,
    hp: null,
    specification: "Add 2 HP to your god.",
    faction: "Citizen",
    rarity: "Rare",
    cardType: "Spell",
    life: "",
    strength: "",
    power: "",
    sellerFeeBasisPoints: "",
    creatorAddress: "",
    creatorShare: "",
    fileUri: "",
    fileType: "",
  },
  {
    name: "Random Function",
    image: "",
    description: "",
    symbol: "",
    collectionName: "",
    collectionFamily: "",
    mana: 3,
    attack: null,
    hp: null,
    specification: "Decrease the mana cost of a random card in your hand by 2 points.",
    faction: "Magic",
    rarity: "Common",
    cardType: "Spell",
    life: "",
    strength: "",
    power: "",
    sellerFeeBasisPoints: "",
    creatorAddress: "",
    creatorShare: "",
    fileUri: "",
    fileType: "",
  },
  {
    name: "Stablecoin",
    image: "",
    description: "",
    symbol: "",
    collectionName: "",
    collectionFamily: "",
    mana: 2,
    attack: null,
    hp: null,
    specification: "Add 1 HP to all friendly minions.",
    faction: "Magic",
    rarity: "Common",
    cardType: "Spell",
    life: "",
    strength: "",
    power: "",
    sellerFeeBasisPoints: "",
    creatorAddress: "",
    creatorShare: "",
    fileUri: "",
    fileType: "",
  },
  {
    name: "Regulatooor",
    image: "",
    description: "",
    symbol: "",
    collectionName: "",
    collectionFamily: "",
    mana: 6,
    attack: null,
    hp: null,
    specification: "- 3 HP to all opponent minions.",
    faction: "Citizen",
    rarity: "Legendary",
    cardType: "Spell",
    life: "",
    strength: "",
    power: "",
    sellerFeeBasisPoints: "",
    creatorAddress: "",
    creatorShare: "",
    fileUri: "",
    fileType: "",
  },
  {
    name: "Diamond Hands",
    image: "",
    description: "",
    symbol: "",
    collectionName: "",
    collectionFamily: "",
    mana: 5,
    attack: null,
    hp: null,
    specification: "Draw 2 random cards and unconfuse all friendly minions.",
    faction: "Creature",
    rarity: "Epic",
    cardType: "Spell",
    life: "",
    strength: "",
    power: "",
    sellerFeeBasisPoints: "",
    creatorAddress: "",
    creatorShare: "",
    fileUri: "",
    fileType: "",
  },
  {
    name: "Picker",
    image: "",
    description: "",
    symbol: "",
    collectionName: "",
    collectionFamily: "",
    mana: 3,
    attack: null,
    hp: null,
    specification: "Draw 2 random cards.",
    faction: "Neutral",
    rarity: "Common",
    cardType: "Spell",
    life: "",
    strength: "",
    power: "",
    sellerFeeBasisPoints: "",
    creatorAddress: "",
    creatorShare: "",
    fileUri: "",
    fileType: "",
  },
  {
    name: "Doggo Vision",
    image: "",
    description: "",
    symbol: "",
    collectionName: "",
    collectionFamily: "",
    mana: 4,
    attack: null,
    hp: null,
    specification: "See the top 4 cards of your enemies deck.",
    faction: "Creature",
    rarity: "Common",
    cardType: "Spell",
    life: "",
    strength: "",
    power: "",
    sellerFeeBasisPoints: "",
    creatorAddress: "",
    creatorShare: "",
    fileUri: "",
    fileType: "",
  },
  {
    name: "Burn",
    image: "",
    description: "",
    symbol: "",
    collectionName: "",
    collectionFamily: "",
    mana: 6,
    attack: null,
    hp: null,
    specification: "Destroy the targeted minion and +3 HP to your god.",
    faction: "Creature",
    rarity: "Common",
    cardType: "Spell",
    life: "",
    strength: "",
    power: "",
    sellerFeeBasisPoints: "",
    creatorAddress: "",
    creatorShare: "",
    fileUri: "",
    fileType: "",
  },
  {
    name: "Satcrifice",
    image: "",
    description: "",
    symbol: "",
    collectionName: "",
    collectionFamily: "",
    mana: 1,
    attack: null,
    hp: null,
    specification: "Destroy the targeted minion and draw 2 random cards.",
    faction: "Magic",
    rarity: "Rare",
    cardType: "Spell",
    life: "",
    strength: "",
    power: "",
    sellerFeeBasisPoints: "",
    creatorAddress: "",
    creatorShare: "",
    fileUri: "",
    fileType: "",
  },
  {
    name: "Bags Filled",
    image: "",
    description: "",
    symbol: "",
    collectionName: "",
    collectionFamily: "",
    mana: 2,
    attack: null,
    hp: null,
    specification: "Selected friendly minion attacks all enemy creatures present on the board.",
    faction: "Neutral",
    rarity: "Rare",
    cardType: "Spell",
    life: "",
    strength: "",
    power: "",
    sellerFeeBasisPoints: "",
    creatorAddress: "",
    creatorShare: "",
    fileUri: "",
    fileType: "",
  },
  {
    name: "Shiba Riot",
    image: "",
    description: "",
    symbol: "",
    collectionName: "",
    collectionFamily: "",
    mana: 3,
    attack: null,
    hp: null,
    specification: "Reset attack and HP to base for all friendly creatures and remove any Freeze and Confuse.",
    faction: "Evil",
    rarity: "Rare",
    cardType: "Spell",
    life: "",
    strength: "",
    power: "",
    sellerFeeBasisPoints: "",
    creatorAddress: "",
    creatorShare: "",
    fileUri: "",
    fileType: "",
  },
  {
    name: "Double Spend",
    image: "",
    description: "",
    symbol: "",
    collectionName: "",
    collectionFamily: "",
    mana: 4,
    attack: null,
    hp: null,
    specification: "Deal 3 Damage to a targeted minion along with the enemy god.",
    faction: "Neutral",
    rarity: "Rare",
    cardType: "Spell",
    life: "",
    strength: "",
    power: "",
    sellerFeeBasisPoints: "",
    creatorAddress: "",
    creatorShare: "",
    fileUri: "",
    fileType: "",
  },
  {
    name: "Gaeam",
    image: "",
    description: "",
    symbol: "",
    collectionName: "",
    collectionFamily: "",
    mana: null,
    attack: null,
    hp: 30,
    specification: "Enemy creatures go to Sleep",
    faction: null,
    rarity: null,
    cardType: "God",
    life: "",
    strength: "",
    power: "",
    sellerFeeBasisPoints: "",
    creatorAddress: "",
    creatorShare: "",
    fileUri: "",
    fileType: "",
  },
  {
    name: "Myx",
    image: "",
    description: "",
    symbol: "",
    collectionName: "",
    collectionFamily: "",
    mana: null,
    attack: null,
    hp: 30,
    specification: "Give -1 HP to each ennemy minions.",
    faction: null,
    rarity: null,
    cardType: "God",
    life: "",
    strength: "",
    power: "",
    sellerFeeBasisPoints: "",
    creatorAddress: "",
    creatorShare: "",
    fileUri: "",
    fileType: "",
  },
  {
    name: "Cosmas",
    image: "",
    description: "",
    symbol: "",
    collectionName: "",
    collectionFamily: "",
    mana: null,
    attack: null,
    hp: 30,
    specification: "Give +1 HP to each friendly minions.",
    faction: null,
    rarity: null,
    cardType: "God",
    life: "",
    strength: "",
    power: "",
    sellerFeeBasisPoints: "",
    creatorAddress: "",
    creatorShare: "",
    fileUri: "",
    fileType: "",
  },
  {
    name: "Anamke",
    image: "",
    description: "",
    symbol: "",
    collectionName: "",
    collectionFamily: "",
    mana: null,
    attack: null,
    hp: 30,
    specification: "Add 2 mana for the current turn",
    faction: null,
    rarity: null,
    cardType: "God",
    life: "",
    strength: "",
    power: "",
    sellerFeeBasisPoints: "",
    creatorAddress: "",
    creatorShare: "",
    fileUri: "",
    fileType: "",
  },
];